apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-db-config
data:
  MYSQL_USER: value_can_be_replaced
  MYSQL_ROOT_PASSWORD: value_can_be_replaced
  MYSQL_PASSWORD: value_can_be_replaced
  MYSQL_DATABASE: value_can_be_replaced
