version: '3.9'

services:
  db:
    image: mysql:latest
    container_name: locallib-db
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - djangoNet
    volumes:
      - /home/shihab1/docker-pr-now/locallibDb:/var/lib/mysql
  web:
    build: .
    container_name: locallib-web
    command: python manage.py runserver 0.0.0.0:6080
    volumes:
      - /home/shihab1/docker-pr-now/app/locallib:/locallib
    ports:
      - 6080:6080
    depends_on:
      - db
    networks:
      - djangoNet

networks:
  djangoNet:
